# Generated by Django 4.1.1 on 2022-12-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_photo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
